[package]
name = "http-plz"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
header-plz = "0.0.36"
# header-plz = { git = "https://github.com/parseplz/primitives.git" }
body-plz = "0.0.40"
decompression-plz = "0.0.17"
thiserror = "2.0.17"
